### ISSUE TITLE
some thing about the dataset

### ISSUE THREAD

**Issue by supportingvector** [ananyahjha93/cycle-consistent-vae#2]
Hello, I find your work interesting. But it seems you only provide the code and the dataset of MNIST. I wonder if you could provide the Sprites and LineMod as well.

**Comment by ananyahjha93** [comment]
You just need to change the networks.py and dataloader.py files to suit your own dataset. The training procedure remains the same. The other code is not included for this very reason because it makes it redundant to upload multiple versions of networks.py and dataloader.py.
